import type { Chat, Message, TelegramSnapshot, User } from "./types";

const users: User[] = [
  {
    id: "self",
    displayName: "林然",
    avatar: { label: "林", color: "#d16f45" },
    presence: "online",
  },
  {
    id: "u-mia",
    displayName: "Mia Chen",
    avatar: { label: "MC", color: "#397a78" },
    presence: "online",
  },
  {
    id: "u-chen",
    displayName: "陈默",
    avatar: { label: "陈", color: "#75579a" },
    presence: "offline",
    lastSeenLabel: "30 分钟前在线",
  },
  {
    id: "u-jules",
    displayName: "Jules",
    avatar: { label: "J", color: "#3f6e9d" },
    presence: "typing",
  },
];

const chats: Chat[] = [
  {
    id: "chat-product",
    kind: "group",
    folder: "main",
    title: "产品讨论",
    avatar: { label: "产", color: "#207d75" },
    preview: "Jules：我把交互稿更新到最新版本了",
    updatedAt: "2026-08-01T09:48:00+08:00",
    unreadCount: 3,
    pinned: true,
    muted: false,
  },
  {
    id: "chat-mia",
    kind: "direct",
    folder: "main",
    title: "Mia Chen",
    avatar: { label: "MC", color: "#397a78" },
    peerId: "u-mia",
    preview: "那我们下午三点对一下细节",
    updatedAt: "2026-08-01T09:32:00+08:00",
    unreadCount: 1,
    pinned: true,
    muted: false,
  },
  {
    id: "chat-saved",
    kind: "saved",
    folder: "main",
    title: "收藏夹",
    avatar: { label: "我", color: "#d16f45" },
    preview: "TDLib integration notes.md",
    updatedAt: "2026-08-01T08:15:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: false,
  },
  {
    id: "chat-chen",
    kind: "direct",
    folder: "main",
    title: "陈默",
    avatar: { label: "陈", color: "#75579a" },
    peerId: "u-chen",
    preview: "收到，我今晚看一下",
    updatedAt: "2026-07-31T22:40:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: true,
  },
  {
    id: "chat-release",
    kind: "channel",
    folder: "main",
    title: "Release Notes",
    avatar: { label: "R", color: "#b76a3a" },
    preview: "Desktop build 0.8.4 is ready",
    updatedAt: "2026-07-31T18:06:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: true,
  },
  {
    id: "chat-archive",
    kind: "group",
    folder: "archive",
    title: "旧项目同步",
    avatar: { label: "旧", color: "#687477" },
    preview: "归档前请检查共享文件",
    updatedAt: "2026-07-23T14:20:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: true,
  },
];

const messages: Message[] = [
  {
    id: "p-1",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:18:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "早上好，左侧会话列表的密度已经调整好了。" },
  },
  {
    id: "p-2",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:24:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "看到了。消息区再留一点呼吸感，信息密度就比较平衡。" },
  },
  {
    id: "p-3",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:35:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "desktop-layout-review.pdf",
      sizeLabel: "2.4 MB",
    },
  },
  {
    id: "p-4",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "我把交互稿更新到最新版本了，下午可以直接走查。" },
  },
  {
    id: "m-1",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:10:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "登录流程先覆盖手机号、验证码和二步验证，对吗？" },
  },
  {
    id: "m-2",
    chatId: "chat-mia",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:20:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "对，QR 登录放在下一轮，不影响主链路。" },
  },
  {
    id: "m-3",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:32:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "那我们下午三点对一下细节。" },
  },
  {
    id: "s-1",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T08:15:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "TDLib integration notes.md",
      sizeLabel: "18 KB",
    },
  },
  {
    id: "c-1",
    chatId: "chat-chen",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-07-31T22:35:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "原生桥接接口我先按事件流来设计。" },
  },
  {
    id: "c-2",
    chatId: "chat-chen",
    senderId: "u-chen",
    outgoing: false,
    sentAt: "2026-07-31T22:40:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "收到，我今晚看一下。" },
  },
];

export const mockSnapshot: TelegramSnapshot = {
  currentUserId: "self",
  authorization: { kind: "ready" },
  users,
  chats,
  messages,
};
