import type { Chat, Message, TelegramSnapshot, User } from "./types";
import mediaPreviewUrl from "../../src-tauri/icons/icon.png";

const tallMediaPreviewUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`
  <svg xmlns="http://www.w3.org/2000/svg" width="900" height="1800" viewBox="0 0 900 1800">
    <rect width="900" height="1800" fill="#173b4c"/>
    <rect x="70" y="70" width="760" height="1660" rx="48" fill="#ecf3f1"/>
    <rect x="125" y="145" width="650" height="660" rx="28" fill="#2c8f86"/>
    <rect x="125" y="865" width="650" height="54" rx="18" fill="#173b4c"/>
    <rect x="125" y="965" width="520" height="34" rx="14" fill="#89aaa4"/>
    <rect x="125" y="1040" width="610" height="34" rx="14" fill="#89aaa4"/>
    <rect x="125" y="1115" width="475" height="34" rx="14" fill="#89aaa4"/>
  </svg>
`)}`;

const users: User[] = [
  {
    id: "self",
    displayName: "林然",
    avatar: { label: "林", color: "#d16f45" },
    presence: "online",
  },
  {
    id: "u-mia",
    displayName: "Mia Chen",
    avatar: { label: "MC", color: "#397a78" },
    presence: "online",
  },
  {
    id: "u-chen",
    displayName: "陈默",
    avatar: { label: "陈", color: "#75579a" },
    presence: "offline",
    lastSeenLabel: "30 分钟前在线",
  },
  {
    id: "u-jules",
    displayName: "Jules",
    avatar: { label: "J", color: "#3f6e9d" },
    presence: "typing",
  },
];

const chats: Chat[] = [
  {
    id: "chat-product",
    kind: "group",
    folderIds: ["main", "folder:work"],
    title: "产品讨论",
    avatar: { label: "产", color: "#207d75" },
    preview: "Jules：我把交互稿更新到最新版本了",
    updatedAt: "2026-08-01T09:48:00+08:00",
    unreadCount: 3,
    pinned: true,
    pinnedFolderIds: ["main", "folder:work"],
    listOrderByFolder: { main: "200", "folder:work": "200" },
    muted: false,
  },
  {
    id: "chat-mia",
    kind: "direct",
    folderIds: ["main"],
    title: "Mia Chen",
    avatar: { label: "MC", color: "#397a78" },
    peerId: "u-mia",
    preview: "那我们下午三点对一下细节",
    updatedAt: "2026-08-01T09:32:00+08:00",
    unreadCount: 1,
    pinned: true,
    pinnedFolderIds: ["main"],
    listOrderByFolder: { main: "100" },
    muted: false,
  },
  {
    id: "chat-saved",
    kind: "saved",
    folderIds: ["main"],
    title: "收藏夹",
    avatar: { label: "我", color: "#d16f45" },
    preview: "TDLib integration notes.md",
    updatedAt: "2026-08-01T08:15:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: false,
  },
  {
    id: "chat-chen",
    kind: "direct",
    folderIds: ["main"],
    title: "陈默",
    avatar: { label: "陈", color: "#75579a" },
    peerId: "u-chen",
    preview: "收到，我今晚看一下",
    updatedAt: "2026-07-31T22:40:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: true,
  },
  {
    id: "chat-release",
    kind: "channel",
    folderIds: ["main", "folder:work"],
    title: "Release Notes",
    avatar: { label: "R", color: "#b76a3a" },
    preview: "Desktop build 0.8.4 is ready",
    updatedAt: "2026-07-31T18:06:00+08:00",
    unreadCount: 8,
    pinned: false,
    muted: true,
  },
  {
    id: "chat-archive",
    kind: "group",
    folderIds: ["archive"],
    title: "旧项目同步",
    avatar: { label: "旧", color: "#687477" },
    preview: "归档前请检查共享文件",
    updatedAt: "2026-07-23T14:20:00+08:00",
    unreadCount: 0,
    pinned: false,
    muted: true,
  },
];

const olderProductMessages: Message[] = Array.from({ length: 36 }, (_, index) => ({
  id: `p-old-${index + 1}`,
  chatId: "chat-product",
  senderId: index % 2 === 0 ? "u-jules" : "self",
  outgoing: index % 2 !== 0,
  sentAt: new Date(Date.UTC(2026, 6, 30, 0, index)).toISOString(),
  delivery: "read",
  content: { kind: "text", text: `产品讨论历史消息 ${index + 1}` },
}));

const messages: Message[] = [
  ...olderProductMessages,
  {
    id: "p-service",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:00+08:00",
    delivery: "read",
    content: { kind: "service", text: "Mia Chen 加入了群聊" },
  },
  {
    id: "p-rich-message",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:30+08:00",
    delivery: "read",
    content: {
      kind: "rich",
      isRtl: false,
      isFull: true,
      text: [
        "今日小贴士",
        "保持专注，也别忘了适当休息。",
        "优先处理最重要的一件事",
        "喝点水，活动一下身体",
        "晚上给自己留一点放松时间",
        "慢一点没关系，持续前进就很好。",
        "输入　5,709 tokens 缓存输入　3,712 tokens 输出　68 tokens",
        "Bot API 10.2",
        "E = mc^2",
        "Status Ready",
        "Advanced details",
      ].join("\n"),
      blocks: [
        { kind: "heading", level: 1, text: [{ text: "今日小贴士" }] },
        { kind: "paragraph", text: [{ text: "保持专注，也别忘了适当休息。" }] },
        {
          kind: "list",
          ordered: false,
          items: [
            {
              blocks: [{ kind: "paragraph", text: [{ text: "优先处理最重要的一件事", bold: true }] }],
              hasCheckbox: false,
              checked: false,
            },
            {
              blocks: [{ kind: "paragraph", text: [{ text: "喝点水，活动一下身体" }] }],
              hasCheckbox: false,
              checked: false,
            },
            {
              blocks: [{ kind: "paragraph", text: [{ text: "晚上给自己留一点放松时间" }] }],
              hasCheckbox: false,
              checked: false,
            },
          ],
        },
        {
          kind: "quote",
          pull: false,
          blocks: [{ kind: "paragraph", text: [{ text: "慢一点没关系，持续前进就很好。" }] }],
        },
        {
          kind: "quote",
          pull: false,
          blocks: [{
            kind: "paragraph",
            text: [
              { text: "输入", bold: true },
              { text: "　" },
              { text: "5,709 tokens", code: true },
              { text: " 缓存输入", bold: true },
              { text: "　" },
              { text: "3,712 tokens", code: true },
              { text: " 输出", bold: true },
              { text: "　" },
              { text: "68 tokens", code: true },
            ],
          }],
        },
        {
          kind: "paragraph",
          text: [
            { text: "", anchor: { kind: "anchor", name: "bot-api" } },
            { text: "Bot API 10.2", marked: true },
            { text: " ✨", customEmojiId: "5368324170671202286" },
            { text: " jump", linkTarget: { kind: "anchor", name: "bot-api" } },
          ],
        },
        { kind: "mathematicalExpression", expression: "E = mc^2" },
        {
          kind: "table",
          caption: [{ text: "Status" }],
          bordered: true,
          striped: true,
          rows: [[
            {
              text: [{ text: "Metric", bold: true }],
              header: true,
              colspan: 1,
              rowspan: 1,
              visible: true,
              align: "left",
              valign: "middle",
            },
            {
              text: [{ text: "Ready", spoiler: true }],
              header: false,
              colspan: 1,
              rowspan: 1,
              visible: true,
              align: "center",
              valign: "middle",
            },
          ]],
        },
        {
          kind: "details",
          summary: [{ text: "Advanced" }],
          blocks: [{ kind: "paragraph", text: [{ text: "Advanced details" }] }],
          open: false,
        },
        {
          kind: "media",
          media: {
            mediaType: "photo",
            fileName: "Bot chart",
            sizeLabel: "18 KB",
            localPath: "/mock-video-poster.jpg",
            isDownloaded: true,
            hasSpoiler: false,
            autoplay: false,
            loop: false,
            width: 640,
            height: 360,
            caption: { text: [{ text: "Rich media block" }] },
          },
        },
      ],
    },
  },
  {
    id: "p-unknown",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:45+08:00",
    delivery: "read",
    content: {
      kind: "unsupported",
      type: "messageFutureType",
      text: "收到新类型消息（messageFutureType）",
      raw: JSON.stringify({
        "@type": "message",
        id: "p-unknown",
        chat_id: "chat-product",
        content: {
          "@type": "messageFutureType",
          payload: { example: true },
        },
      }, null, 2),
    },
  },
  {
    id: "p-1",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:18:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "早上好，左侧会话列表的密度已经调整好了。" },
  },
  {
    id: "p-2",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:24:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "看到了。消息区再留一点呼吸感，信息密度就比较平衡。" },
  },
  {
    id: "p-3",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:35:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "desktop-layout-review.pdf",
      sizeLabel: "2.4 MB",
      fileId: 42,
      size: 2_516_582,
      localPath: "/mock-file.pdf",
      canDownload: false,
      isDownloading: false,
      isDownloaded: true,
    },
  },
  {
    id: "p-file-downloading",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:36:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "research-notes.zip",
      sizeLabel: "12.8 MB",
      fileId: 43,
      size: 13_421_772,
      canDownload: true,
      isDownloading: true,
      isDownloaded: false,
      progress: 0.48,
    },
  },
  {
    id: "p-4",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "我把交互稿更新到最新版本了，下午可以直接走查。" },
  },
  {
    id: "p-markdown",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:20+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: "**Markdown 粗体**、*斜体*、~~删除线~~\n\n- 支持列表\n- 支持 `code` 与 [链接](https://example.com)",
    },
  },
  {
    id: "p-rich-entities",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:40+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: "TDLib bold link",
      entities: [
        { offset: 6, length: 4, kind: "bold" },
        { offset: 11, length: 4, kind: "textUrl", href: "https://example.com/rich" },
      ],
    },
  },
  {
    id: "p-tall",
    chatId: "chat-product",
    mediaAlbumId: "mock-album-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:49:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "纵向图片.jpg",
      sizeLabel: "220 KB",
      previewDataUrl: tallMediaPreviewUrl,
      width: 512,
      height: 512,
      caption: "纵向图片应该按实际比例收窄，外壳不能留下额外空白。",
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "p-5",
    chatId: "chat-product",
    mediaAlbumId: "mock-album-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:50:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "界面预览.jpg",
      sizeLabel: "186 KB",
      previewDataUrl: mediaPreviewUrl,
      width: 512,
      height: 512,
      caption: "新的媒体预览样式",
      isDownloaded: false,
      isDownloading: true,
      progress: 0.62,
    },
  },
  {
    id: "p-video",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:51:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "video",
      fileName: "交互预览.mp4",
      sizeLabel: "278 KB",
      fileId: 93,
      size: 283_989,
      mimeType: "video/mp4",
      previewDataUrl: "/mock-video-poster.jpg",
      width: 640,
      height: 360,
      caption: "这是昨晚导出的交互录屏，麻烦确认最后一段。",
      captionEntities: [{ offset: 2, length: 2, kind: "bold" }],
      canDownload: true,
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "p-audio",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:50:30+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "voice",
      fileName: "产品语音.m4a",
      sizeLabel: "278 KB",
      fileId: 94,
      size: 283_989,
      mimeType: "audio/mp4",
      localPath: "/mock-video.mp4",
      canDownload: true,
      isDownloaded: true,
      isDownloading: false,
    },
  },
  {
    id: "m-1",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:10:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "登录流程先覆盖手机号、验证码和二步验证，对吗？" },
  },
  {
    id: "m-2",
    chatId: "chat-mia",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:20:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "对，QR 登录放在下一轮，不影响主链路。" },
  },
  {
    id: "m-3",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:32:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "那我们下午三点对一下细节。" },
  },
  {
    id: "s-2",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: false,
    sentAt: "2026-08-01T08:16:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "收藏夹方向测试" },
  },
  {
    id: "s-1",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T08:15:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "TDLib integration notes.md",
      sizeLabel: "18 KB",
    },
  },
  {
    id: "c-1",
    chatId: "chat-chen",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-07-31T22:35:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "原生桥接接口我先按事件流来设计。" },
  },
  {
    id: "c-2",
    chatId: "chat-chen",
    senderId: "u-chen",
    outgoing: false,
    sentAt: "2026-07-31T22:40:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "收到，我今晚看一下。" },
  },
];

export const mockSnapshot: TelegramSnapshot = {
  currentUserId: "self",
  authorization: { kind: "ready" },
  users,
  folders: [
    { id: "main", title: "全部聊天", iconName: "All" },
    { id: "folder:work", title: "工作", iconName: "Custom" },
    { id: "archive", title: "归档", iconName: "Archive" },
  ],
  chats,
  messages,
};
